---
# This is an example of yaml configuration file for bilipod.

# Web server related configuration.
server:
  # HTTP server port.
  port: 5728

  # Optional. If you want to hide Podsync behind reverse proxy like nginx, you can use this field.
  # Server will be accessible from http://{bind_address}:{port}, but episode links will point to this URL {hostname}.
  hostname: "https://example.com:5728"
  # Bind a specific IP addresses for server, default is to bind localhost or  
  bind_address: "0.0.0.0"
  # Specify path for reverse proxy, default is "/" and only [A-Za-z0-9] is allowed.
  # path: "test"
  # Optional. If you want to use TLS, you must set the TLS flag and specify the certificate file and private key file.
  tls: false
  certificate_path: ""
  key_file_path: ""


# Configure where to store the episode data
storage:
  # Could be "local" (default) for the local file system
  type: local
  storage.local:
    data_dir: /app/data # Don't change if you run podsync via docker

token:
  # This is the token used to authenticate with the bilibili API
  # refer to https://nemo2011.github.io/bilibili-api/#/get-credential for more details
  bili_jct:
  buvid3:
  buvid4: # optional
  dedeuserid:
  sessdata:
  ac_time_value: # optional
  cookie_file_path: # optional, use this if you want to use exported Netscape cookies

login:
  # Optional. If you want to use bilibili account info (e.g. username, password, phone number) to login, you can set this field.
  username:
  password:
  phone_number:
  country_code: # default is +86

feeds:
  xiaoyuehankehan:
    # choose one of the following two options
    # user_id (uid) or playlist_id (sid)
    uid: 23947287 # e.g. https://space.bilibili.com/23947287

    # sid: 1733148 e.g. https://space.bilibili.com/1544008396/lists/1733148?type=season or https://space.bilibili.com/1724598/lists/224631?type=series
    # playlist_type: season # season or series, default season, only apply to sid

    # The number of episodes to query each update (keep in mind, that this might cause IP ban), default 10
    page_size: 5

    # How often query for updates, examples: "60m", "4h", "2h45m", default "12h"
    update_period: 1m

    format: audio # "audio" or "video", default "audio"

    playlist_sort: "desc" #  which will fetch playlist items from the end, only support "desc" now

    quality: low # or median , or high, default "low"

    # Optionally include this feed in OPML file (default value: true)
    opml: True

    # Whether to cleanup old episodes.Default keep last 10 episodes if true. (order desc by PubDate)
    keep_last: 10 # the number of episodes to keep or "None" to keep all , default 10

    # Optional keywords
    keyword: # Name match to serch for. If set, then only download matching episodes. e.g. "硬核狠人"; Not working with playlist; Sort is not supported with keyword

    # When set to true, podcasts indexers such as iTunes or Google Podcasts will not index this podcast, default true
    private_feed: True

    # Option to endorse the video, default None, or list of ['like','coin|{number(1 or 2)}','favorite|{media_id}'], or “triple”, for media_id, refer to https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/fav/info.md
    endorse: # ['like','coin|2','favorite|{media_id}']

    # Optional feed customizations
    title: # "小约翰可汗-硬核狠人"
    description: # "等待鸽多"
    author: # "小约翰可汗"
    cover_art: # "{IMAGE_URL}"
    category: # "TV"
    subcategories: # "Documentary", "Tech News"
    explicit: # no
    lang: # "en"
    # optional: this will override the default link (usually the URL address) in the generated RSS feed with another link
    link: # "https://example.org"


# Optional log config. If not specified logs to the stdout
log:
  filename : "/app/logs/bilipod.log"
  max_size : 50 # MB
  max_age : 30 # days
  compress : true
  debug : false