version: '3.8'

services:
  bilipod:
    image: sunrisewestern/bilipod:latest
    container_name: bilipod
    ports:
      - "7001:5728"
    volumes:
      - ./config_docker.yaml:/app/config.yaml
      - ./data:/app/data
      - ./logs:/app/logs

    restart: unless-stopped