version: '3.8'

services:
  bilipod:
    image: sunrisewestern/bilipod:latest
    container_name: bilipod
    ports:
      - "5728:5728"
      - "41942:41942" # geetest login
      - "41943:41943" # geetest verify
      - "41944:41944" # qr code login
    volumes:
      - ./config_docker.yaml:/app/config.yaml
      - ./data:/app/data
      - ./logs:/app/logs

    restart: unless-stopped
